fname: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened

jobs:
  assign_label:
    runs-on: macos-latest
    steps:
        - name: Assing Label
          env:
            TITLE: ${{ github.event.issue.title }}
          run: |
            if [[ "$TITLE" == *"bug"* ]]; then
            echo "Issue is about a bug"
            else
            echo "Issue is not about a bug"
            fi

