name: Status Check Functions
on: [push]
run-name: "Status Check Functions"

jobs:
    job-1:
        runs-on: macos-latest
        steps:
            - name: Step 1
              run: sleep 20
#            - name: Fail
#              run: exit 1
            - name: Runs on Failure
              if: failure() # return true if any of previous step has failed
              run: echo 'Runs only on failure'
            - name: Runs on Success
              # this is not needed (DEFAULT BEHAVIOUR)
              if: success()
              run: echo 'Runs on Success'
            - name: Always Runs
              if: always()
              run: echo 'Always Runs'
            - name: Runs When Cancelled
              if: cancelled()
              run: echo 'Runs on Cancelled'

    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo 'Job 2'





