name: 'Get & Cache Dependecies'
description: 'Get the dependencies (via podfile) and cache them'
inputs:
    cachinggg:
        description: 'Whether to cache dependecies or not'
        required: false
        # true - user must provide a value in the workflow using this action
        # false - valus is not actually needed
        default: 'true' # can set any value, not only true,false...

outputs:
    used-cache:
        description: 'Whether the cache was used'
        value: ${{ steps.installDp.outputs.cache }}


runs:
    using: 'composite'
    steps:
        - name: Cache dependencies
          if: inputs.cachinggg == 'true'
          id: cacheID
          uses: actions/cache@v3
          with:
            path: github-actions/Pods
            key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
            # restore-keys: |
            #     ${{ runner.os }}-pods-

        - name: Install pod dependencies
          id: installDep
          if: steps.cache.outputs.cache-hit != 'true' || inputs.cachinggg != 'true'
          run: |
                cd github-actions
                pod install
                echo "cache=${{ inputs.cachinggg }}" >> $GITHUB_OUTPUT
          shell: bash

