name: Using reusable workflow
on:
    push:
        branches:
            - main

jobs:
    start:
        runs-on: macos-latest
        steps:
            - name: Output info
              run: echo "Deploying and uploading (step 1)"
              
    deploy:
        needs: start
        uses: ./.github/workflows/9-reusable.yml 
