name: Using reusable workflow
on:
    push:
        branches:
            - main

jobs:
    start:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
      
            - name: List directory contents
              run: ls
              
            - name: Archive artifact
              uses: actions/upload-artifact@v2
              with:
                    name: ios-info-files
                    path: ./github-actions/github-actions/Resources/configuration.json
              
    deploy:
        needs: start
        uses: ./.github/workflows/9-reusable.yml
        with:
            artifact-name: ios-info-files
    
    print-deploy-result:
        needs: deploy
        runs-on: macos-latest
        step:
            - name: Print deploy output LAST
              run: echo "${{ needs.deploy.outputs.result }}"
            
        
        
        
        
        
        
        
        
        
        
        
