name: Using reusable workflow
on:
    push:
        branches:
            - main

jobs:
    start:
        runs-on: macos-latest
        steps:
            - name: Output info
              run: ls
              
            - name: Archive artifact
              uses: actions/upload-artifact@v2
              with:
                name: ios-info-files
                path: ./github-actions/github-actions/github-actions/Resources/configuration.json
              
    deploy:
        needs: start
        uses: ./.github/workflows/9-reusable.yml
        with:
            artifact-namexxx: ios-info-files
            
        
        
        
        
        
        
        
        
        
        
        
