name: Set Bug Label on New Issue

on:
  issues:
    types: [opened]

jobs:
  set_bug_label:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the issue title contains 'bug'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = github.context.payload.issue.title;
            const containsBug = issueTitle.toLowerCase().includes('bug');
            if (containsBug) {
              const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
              await octokit.rest.issues.addLabels({
                owner: github.context.payload.repository.owner.login,
                repo: github.context.payload.repository.name,
                issue_number: github.context.payload.issue.number,
                labels: ['bug']
              });
            }
