name: Outputs
on:
    pull_request:
        branches:
            - main

env:
    GIT_DB_NAME: GitActions Data Base
    GIT_USERNAME: Username Git
    GIT_PASSWORD: Qwerty123
    GIT_JOB_PORT: 8080
    GIT_ACTION_SECRET: ${{ secrets.GIT_ACTION_SECRET }}

jobs:
    build:
        env:
            GIT_BUILD_ENV_TITLE: abc
        environment: testing # see the name of env that had been set in github repository settings
        # each environment has its own secrets
            
        runs-on: macos-latest
        outputs:
            name-abc-file: ${{ steps.publishID.outputs.something }}
        steps:
        - name: Get cole
          uses: actions/checkout@v3
          
        - name: List resources
          run: |
            echo "Name 2: "${{ env.GIT_DB_NAME }}"
            echo "The value of GIT_DB_NAME is $GIT_DB_NAME"

