name: Outputs
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: macos-latest
        steps:
        - name: Get code
          id: get-code-step
          uses: actions/checkout@v3
          
        - name: List resources
          if: failure() && steps.get-code-step.outcome == 'failure'
          # failure - will return true if any of other step failure
          run: echo 'Get code'

    report:
        needs: [build]
        if: failure() # will return true if any of other job failure
        runs-on: macos-latest
        steps:
            - name: Output information
              run: |
                echo "Something went wrong here..."
                echo "${{ toJSON(github) }}"
                
                
                
                
                
                
                
                
                
                
                

