name: Matrix
on:
    push:
        branches:
            - main

jobs:
    build:
        strategy:
            matrix:
                xcode: [12.5.1, 13.0]
                operation-system: [ubuntu-latest, macos-latest]
                
        runs-on: ${{ matrix.operation-system }}
        steps:
        - name: Get code
          uses: actions/checkout@v3
          
        - name: List resources
          run: echo 'List resources'


                
                
                
                
                
                
                
                
                
                

