name: Reusable workflow
# workflow_call allows to call this workflow from another workflows

on:
    workflow_call:
        inputs: # reserved word here
            artifact-name: # your word here
                description: the name of deployable artifact file
                required: true
                # required true - the value is needed from artifact name
                # required false - can be called without providing and input value from artifact name
                default: dist # can be any word here
                type: string # expected type of value here
        outputs:
            result:
                description: The result of deployment
                value: ${{ jobs.deploy.outputs.outcome }}
            
jobs:
    deploy:
    runs-on: macos-latest
    outputs:
        outcome: ${{ steps.set-result.outputs.step-resulttt }}
        
        steps:
            - name: Echo...
              run: echo inputs.artifact-name
              
            - name: Get Code
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
                
            - name: List files
              run: ls
                
            - name: Output info
              run: echo "Deploying and uploading (step 2)"
              
            - name: Set result output
              id: set-result
              run: echo "step-resulttt=success" >> $GITHUB_OUTPUT
              
