name: Reusable workflow
# workflow_call allows calling this workflow from other workflows

on:
  workflow_call:
    inputs:
      artifact-name:
        description: the name of the deployable artifact file
        required: true
        default: dist
        type: string
    outputs:
      result:
        description: The result of deployment
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    runs-on: macos-latest
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    steps:
      - name: Echo Artifact Name
        run: echo ${{ inputs.artifact-name }}
              
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
                
      - name: List files
        run: ls
                
      - name: Output info
        run: echo "Deploying and uploading (step 2)"
              
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_ENV
