name: Actions

# filtering params
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
on:
    release:
        branches:
            - master
            - 'feature/*' # matches feature/featA, feature/featB, does not match feature/feat/a
            - 'feature/**' # matches feature/featA, feature/featB feature/feat/a
            - '!feature/featC' # ignore this branch even if it is match with both abouve patterns
#        branches-ignore: # cannot use `branches` and `branches-ignore` at the same tine
#            - null

        tags:
            - v1.* # trigger workflow only if repo has v1.* tag
        paths:
            - '**.js' # trigger workflow only if repo has changed any .js file
            - '!filename.js' # ignore a filename.js - will run will all js scipt file except filename

#        paths-ignore: # cannot use `paths` and `paths-ignore` at the same tine
#            - '**.js'


# on:
# # workflow can be trigerred manually by sending post request (outside of github)
# # https://www.udemy.com/course/github-actions/learn/lecture/17389694#overview
# # you can also add some payload, an extra information for running workflow
#     repository_dispatch:
#         types: [build]

#instead of passing the array we here (on:) we can add object
#on: [push, pull_request]

## pull request can have many activity types
## if we do not specifiy these types then pr will trigger workflow only in 3 state (open, sync, reopen)
#on:
#    push: #push does not have any activity types
#    pull_request: # pr has some activity types
#        types: [closed, assigned, opened, reopened]

#on:
#    pull_request:
#        schedule:
#            - cron: "5 * * * *" # 2023-05-22 10:05:00 - minimun 5 minutes
#            - cron: "* * * * 1-3" # At every minute on every day-of-week from Monday through Wednesday
#            - cron: "0 12 3 4 2" # At 12:00 on day-of-month 3 and on Tuesday in April.
#            - cron: "0 12 * JAN 0" # At 12:00 on Sunday in January
#            - cron: "0/5 * * * *" # At every 5th minute from 0 through 59

# Jobs

jobs:
  run-github-actions:
    runs-on: macos-latest
    steps:
        - name: Payload
          run: echo ${{ github.event.client_payload.env }}
        - name: List files
          run: |
            pwd
            ls -a
            # $GITHUB_SHA - our last commit which triggered this workflow
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            # $GITHUB_WORKSPACE - the same as pwd command
            echo $GITHUB_WORKSPACE
            echo "{{ github.token }}"

# instead of actions/checkout@v1 you can trigger it manually, see below
# this is not accuate command, just to show how can we make checkout without actions/checkout@v1
#          git clone git@github:denis-huma/github-actions-test
#          git checkout $GITHUB_SHA

        - name: Checkout
          uses: actions/checkout@v1

        - name: List files after Checkout
          run: |
            pwd
            ls -a

        - name: Simple JS Action
          id: greet
          # you can use version of the action
          uses: actions/hello-world-javascript-action@v1
          #or you can use master branch
          #ses: actions/hello-world-javascript-action@master
          #or you can use special commit
          #ses: actions/hello-world-javascript-action@2b3kd
          with:
            who-to-great: Den # input

        - name: Log greeting time
        # steps - github variable which contains all of the steps
          run: echo "${{ steps.greet.outputs.time }}"

