name: Context testing
on: [release]

jobs:
  functions_job:
    runs-on: macos-latest
    # functions_job will run only when push is triggered
    if: github.event_name == 'push'
    steps:
        - name: functions execution
          run: |
            echo ${{ contains( 'hello', '11' ) }}
            echo ${{ startsWith( 'hello', 'he') }}
            echo ${{ endsWith( 'hello', 'lo') }}
            echo ${{ format('Hello {0} {1} {2}', 'World', '!', '!') }}

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    # needs: ["functions_job"] # the 'dump_contexts_to_log' will not be triggered until 'functions_job' is done

    steps:
    # in expression like ${{function}} we can have functions inside them
      - name: Dump GitHub context

        id: github_context_step
        # this step will not run due to ecccho
        run: ecccho '${{ toJSON(github) }}'

        # when a step fails, any subsequent step will not run
        # but with 'if' statement in next step we can move further even if it step before is failed

      - name: Dump job context
        if: failure() # returns true, when previous step has failed
        # if: success()
        # if: cancel()
        run: echo '${{ toJSON(job) }}'

      - name: Dump steps context
        if: always() # this step will always run no matter of workflow (failure/success/cancel etc.)
        run: echo '${{ toJSON(steps) }}'

      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'

      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'

      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
