name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.3"]
    runs-on: ${{ matrix.os }}
    steps:
#      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
#        with:
#          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3

      - name: Force Xcode 14
        run: sudo xcode-select -switch /Applications/Xcode.app
      - name: iOS build setup
        run: >-
          xcodebuild test -workspace github-actions.xcodeproj/project.xcworkspace
          -scheme github-actions -destination 'platform=iOS Simulator,name=iPhone
          11,OS=16.4'
