name: Delpoy file
on:
    push:
        branches:
            - main
jobs:
    buildxxx:
        runs-on: macos-latest

        outputs:
            script-file-xxx: ${{ steps.publish_xxx.outputs.script-file-xxx }}

        steps:
            - name: Get code
              uses: actions/checkout@v3

            - name: Publish JS filename
              id: publish_xxx
              run: find github-actions/github-actions/*.json -type f -execdir echo 'script-file-xxx={}' >> $GITHUB_OUTPUT ';'

            - name: Uplaod artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifa-files
                path: github-actions/github-actions/test.json
    deploy:
        needs: buildxxx
        runs-on: macos-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v3
              with:
                name: artifa-files

            - name: Output contents from artifa
              run: ls #show all the files from artifa-files.zip

            - name: Output filename
            # needs - docs.github.com/en/actions/learn-github-actions/contexts
              run: echo "${{ needs.buildxxx.outputs.script-file-xxx }}"

            - name: Deploy
              run: echo "Deploying..."


