name: Delpoy file
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Uplaod artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifa-files
                path: github-actions/test.json
    deploy:
        needs: build
        runs-on: macos-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v3
              with:
                name: artifa-files

            - name: Output contents
              run: ls #show all the files from artifa-files.zip
            - name: Deploy
              run: echo "Deploying..."


