name: Delpoy file
on:
    push:
        branches:
            - main
jobs:
    buildxxx:
        runs-on: macos-latest

        outputs:
            script-file-xxx: ${{ steps.publish_xxx.outputs.script-file-xxx }}

        steps:
            - name: Get code
              uses: actions/checkout@v3

              # caching pod install for example
              # must set before install podfile dependecies
              # see extra infor in github.com/actions/cache
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                # specify the files / folder that shoud be cached
                # saved data after current job is done if it does not exist before in this folder
                # but if new dependencies were installed in podfile - then stored new cache
                path: github-actions/Pods
                # key - retrieveing by this key cache for the future
                # may contain dynamic element
                # hashFile() - github function produces an unique value based on file path
                # ** - no matter in which subfolder it might be
                key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
                restore-keys: |
                    ${{ runner.os }}-pods-

            - name: Install pod dependencies
              run: |
                    cd github-actions
                    pod install


            - name: Publish Pod filename
              id: publish_xxx
              run: find github-actions/github-actions/*.json -type f -execdir echo 'script-file-xxx={}' >> $GITHUB_OUTPUT ';'

            - name: Uplaod artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifa-files
                path: |
                    github-actions/github-actions/test.json
                    github-actions/github-actions/Resources
    deployxxx:
        needs: buildxxx
        runs-on: macos-latest
        steps:

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: Pods
                key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
                restore-keys: |
                    ${{ runner.os }}-pods-

            - name: Install pod dependencies
              run: |
                    cd github-actions
                    pod install

            - name: Get build artifacts
              uses: actions/download-artifact@v3
              with:
                name: artifa-files

            - name: Output contents from artifa
              run: ls #show all the files from artifa-files.zip

            - name: Output filename
            # needs - docs.github.com/en/actions/learn-github-actions/contexts
              run: echo "${{ needs.buildxxx.outputs.script-file-xxx }}"

            - name: Deploy
              run: echo "Deploying..."


