name: Workflow2 after Workflow1
on:
#    workflow_dispatch:
    workflow_run:
        workflows: [Repository Events]
        types: [completed]

jobs:
    echo-string:
        runs-on: macos-latest
        steps:
            - run: echo ">>> Triggered because 'Repository Events' was completed >>>"
