name: Pull Request Comment
on: pull_request_target 

jobs:
    pr-comment:
        runs-on: macos-latest
        steps:
            - name: Comment on new PRs
              uses: actions/github-script@v6
              with:
                  script: |
                    github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: '...here is a comment...,
                    });


